runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
service: data-api

runtime_config:
  python_version: 2

resources:
  cpu: 1.0
  memory_gb: 2.0
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 3
  max_num_instances: 13
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

# health_check:
#   enable_health_check: false

#[START env]
env_variables:
    GOOGLE_APPLICATION_CREDENTIALS: "./cred.json"
    API_MODE: 'PROD'
#[END env]
